piggz/harbour-amazfish

translations/harbour-amazfish-ru.ts

I cannot properly test because I do not have the supported watch

Preliminary Russian Translation

---

src/logfetchoperation.cpp

I changed the location of debug logs to QStandardPaths::CacheLocation/logs eg. this case $XDG_CAHE_HOME/$APPNAME/logs.

Use QStandardPaths::CacheLocation/logs as location for log files.

---

translations/harbour-amazfish-de.ts

update german translation

---

ui/translations/harbour-amazfish-ui-fr.ts

Hi,
added French translation.
Cheers,
Nico

Added French translation.

---

daemon/src/deviceinterface.cpp
daemon/src/deviceinterface.h

Hi!
You seem to have had more pressing things to do (or just forgot) than #128, so I gave it a try.
I hope just emitting within the (now renamed) method works for you. 
If you prefer another name or if you think it is done badly in general, please let me know.
A preliminary test resetting the slumber timer with my bip worked well.
cheers,
velox

buttonPressed D-Bus signal

---

daemon/daemon.pro
ui/ui.pro

Without that you only get daemon in default install and that is not what
you want. also get rid of DESTDIR bit, instead use PREFIX, the actual
var for QMAKE is INSTALL_ROOT, DESTDIR is cmake thing.

Install the harbour-amazfish-ui and desktop file

---

documentation/build-instructions.md

This started as fixing a formatting issue and adding the sed one-liner...
Two commands were being merged into one, and a one line sed command to fix the kcoreaddons dependency name issue.
And also now includes some subsequent typos/missing bits found when getting the build working at last ;)

Formatting fix and sed for KCoreAddons fix

---

daemon/src/services/alertnotificationservice.cpp

Another even more trivial one. 
Housekeeping, more or less.
cheers!

Add some sfos specific notification icon definitions

---

documentation/build-instructions.md

I missed a ` and the demon daemon...

build-instructions typos

---

documentation/build-instructions.md

I just had to redo these for the 4.0.1 VM so here is an update

Edit build-instructions for sailfish

---

daemon/src/deviceinterface.cpp
daemon/src/deviceinterface.h
daemon/src/operations/activityfetchoperation.cpp
daemon/src/services/mibandservice.cpp

Only the last commit belongs to this PR

Check the actual time to determine sync times

---

ui/src/harbour-amazfish-ui.cpp

This is, amongst other things, used for the window title

Set applicationDisplayName

---

README.md

Installation instuctions

---

daemon/daemon.pro
daemon/src/deviceinterface.cpp
daemon/src/deviceinterface.h
lib/src/amazfishconfig.h
ui/qml/pages/Settings-app.qml

Simulated event support

---

daemon/src/deviceinterface.cpp

Also, don't use std::sort for eventlist

Don't try to wake up for events without alerts

---

ui/qml/pages/Settings-device.qml
ui/translations/harbour-amazfish-ui-de.ts
ui/translations/harbour-amazfish-ui-nl.ts
ui/ui.pro

Hi,
Added is a Dutch translation.
It is tested and it works.
I was a bit confused that the translation files are not part of the rpm. Do they get installed and are they available to users?

Add Dutch translation, fix German translation

---

documentation/build-instructions.md

This is a slight reorganization of the compilation instructions which might help those that are not familiar with compiling software.

Reorganize build doc for dependency dependencies

---

daemon/src/devices/gtsdevice.cpp

Proposed fix for #253

---

README.md
documentation/build-instructions.md

I spent a bit more time getting Amazfish to work on the PinePhone Pro with Mobian.  I added all of the additional dependencies I needed and noticed a few typos in the process.
Thank you for the amazing project!

Documentation update with additional compilation dependencies and typo fixes.

---

daemon/daemon.pro
daemon/src/devices/pinetimejfdevice.cpp
daemon/src/services/batteryservice.cpp
daemon/src/services/batteryservice.h

I was able to read battery information from pinetime.
See attached screenshot

Read battery level from PineTime

---

ui/translations/harbour-amazfish-ui-cs.ts

some strings are translated incorrectly

fix czech translation

---

daemon/src/services/infinitimeweatherservice.cpp

The temperature should be in Celsius scale and multiplied by 100

---

daemon/src/deviceinterface.cpp
daemon/src/devices/pinetimejfdevice.cpp
lib/src/amazfishconfig.h
ui/qml/pages/Settings-app.qml

make transliteration configurable

---

ui/qml/pages/Settings-alarms.qml
ui/qml/pages/Settings-app.qml
ui/qml/pages/Settings-button-action.qml
ui/qml/pages/Settings-device.qml
ui/qml/pages/Settings-huami-shortcuts.qml
ui/qml/pages/Settings-profile.qml

I am not sure about other user interfaces, but in UT is it better user experience.

trigger pagestack.pop() when save pressed

---

daemon/src/devices/infinitimefirmwareinfo.cpp

Same as GadgetBridge the filename of firmware is used to extract firmware version. See
https://github.com/Freeyourgadget/Gadgetbridge/blob/0f7fa7593130a51d7d95a90301cdfe1bd63ba447/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/pinetime/PineTimeInstallHandler.java#L46

parse pinetime firmware version from filename

---

ui/qml/pages/Settings-profile.qml
ui/qml/pages/StepsPage.qml

I can make up to 700 steps per day since I had leg in the cast. Goal of 5000 steps is unreachable for me. Recovery will takes yet few weeks so I would like to set reasonable goal. In addition to that, the steps graph looks very flat. It would be better to derive maxY from goal

Compute Steps.maxY from fitnessGoal and allow lower goal

---

.github/workflows/sailfishos.yml

- verifies build of sailfishos package
- creates RPM packages for testing
Fixes #313 
I am not able to verify if are packages installable because I don't have SailfishOS device

SailfishOS build using Github Actions

---

rpm/harbour-amazfish.spec

while on the topic of updating things for chum, lets use the newer metadata format.

Update Chum Metadata to new format

---

click/manifest.json.in

Clickable package is using information in click/manifest.json.in

change click version also to 2.2.4

---

ui/harbour-amazfish-ui.desktop

It was selected from https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry

Add Category to .desktop file

---

click/manifest.json.in
rpm/harbour-amazfish.spec
ui/harbour-amazfish-ui.appdata.xml

see https://buildbot.flathub.org/#/builders/37/builds/14520

fix linter warnings

---

ui/amazfish.qrc

Avoid warning introduced in https://github.com/piggz/harbour-amazfish/pull/359

Remove duplicate pics

---

ui/qml/pages/AnalysisPage.qml

I think battery page is enough and it doesn't need to be twice there.

Battery info doesn't need to be twice

---

ui/translations/harbour-amazfish-ui-cs.ts
ui/translations/harbour-amazfish-ui-es.ts
ui/translations/harbour-amazfish-ui-nb_NO.ts

Currently translated at 100.0% (290 of 290 strings)
Translation: Amazfish/UI
Translate-URL: https://hosted.weblate.org/projects/harbour-amazfish/ui/cs/

Translated using Weblate (Czech, Spanish, Norwegian)

---

daemon/daemon.pro
daemon/src/deviceinterface.cpp
rpm/harbour-amazfish.spec

Otherwise there are 3 folders:
```
[root@XperiaXA2 defaultuser]# find /usr/share -name 'harbour-amazfish*' -type d
/usr/share/harbour-amazfish
/usr/share/harbour-amazfish-ui
/usr/share/harbour-amazfishd
```

chirp.raw should be in /usr/share/harbour-amazfishd

---

daemon/translations/harbour-amazfishd-de.ts

Currently translated at 100.0% (29 of 29 strings)
Translation: Amazfish/Daemon
Translate-URL: https://hosted.weblate.org/projects/harbour-amazfish/daemon/de/

daemon: Translated using Weblate (German)

---

README.md

I have spent some time to find out that I need to install some app on bangle.js device

Bangle.js: Improve documentation

---

README.md

With this PR I am adding a note on automatic reconnecting setting in bluetooth settings to readme. I hope this helps others to solve pairing and reconnecting issues.

fix #401 by adding a note on automatic reconnecting to readme

---

lib/src/amazfishconfig.h

This PR will change the default height to something more common than 200cm since I think that is rather not common.

make default height 170cm

---

ui/qml/pages/AnalysisPage.qml
ui/qml/pages/HeartratePage.qml
ui/qml/pages/StepsPage.qml

Just a small thing, but still worth improving. Mainly the graph labels would be nice to make use of translated strings. But I am not sure if e.g. Chinese would translate a unit.

make some labels use the translated string

---

ui/qml/pages/BipFirmwarePage.qml
ui/qml/pages/FirstPage.qml
ui/qml/pages/HeartratePage.qml

The current formula to calculate the maxHR is the oldest and least accurate one. Its also based on a very small number of observations. Although it is mentioned on pretty much all pages on that topic, and its not utterly wrong, most websites agree that this is not the best solution.
The current implementation also has one big flaw: It doesn't cover the case when no date of birth = age is provided in the user data. Then the maxHR is used without any subtractions (age = 0). This leads to a very high maxHR and in the worst case someone may be over straining themself. That's why I think something should be changed.
I did some reading on this, and [Wikipedia](https://en.wikipedia.org/wiki/Heart_rate#Maximum_heart_rate) actually gives a good overview. Interesting, on German webpages, the Sally …

replace Haskell & Fox maxHR formula with more precise Wingate formula

---

ui/qml/pages/Settings-app.qml

I would like to see more details about bluetooth adapter
This change depends on https://github.com/piggz/qble/pull/3

Show bluetooth adapter name, alias, and address

---

ui/harbour-amazfish-ui.appdata.xml

Invalid appdata.xml

---

.github/workflows/ubuntu-touch.yml

I have tried to refresh my previous attempt to build click package with github actions. It seems to be working.

Create CI for Ubuntu Touch

---

daemon/src/devices/huamidevice.cpp
daemon/src/devices/neodevice.cpp
daemon/src/services/miband2service.cpp

Those changes was while searching for https://github.com/piggz/harbour-amazfish/pull/442 . It should help with understanding troubles in future.

Improve logging for huami devices

---

lib/src/amazfish.cpp
ui/qml/pages/HeartratePage.qml
ui/qml/pages/SportsSummaryPage.qml
ui/src/sportsdatamodel.cpp

I was trying to find out reason why the SportSummaryPage is rendered slowly. I have improved code a little. Here are changes explained one by one
Amazfish::activityToString:
- multiple if() changed to switch(). I think it is easier to read and easier for compiler to optimize.
HeartratePage.qml:
- I was confused, because SportsSummary page is loaded already when Heartrate page is shown
- var -> real - for qml compiler are optimizations easier
- `var point = points[i];` In my other project I have spotted significant performance improvement. However, doesn't feel better.
SportsSummaryPage.qml:
- listItem.width -> it was hard to read for me until I figured out that is belongs to previous line.
SportsDataModel::data()
- I have changed condition if (index.row() < 0 || index.row() > …

some refactoring

---

ui/qml/pages/HeartratePage.qml

I have noticed that maxHr() function is called many times upon opening the page. It is enough once.

compute maxHRforAge once

---

ui/qml/pages/Settings-huami-shortcuts.qml

Avoid changing of strings see https://github.com/piggz/harbour-amazfish/pull/461 
This was introduced in https://github.com/piggz/harbour-amazfish/pull/441 
I didn't inspected strings carefully. I am sorry.

Avoid changes in translations

---

daemon/src/devices/banglejsdevice.cpp

I recently got a LilyGo T-Watch 2020 v1. It seems to be compatible with Bangle.js.
After adding these services, notifications started working (at least partially). However, the smartwatch freezes with some unexpected input.
See: https://fosstodon.org/@jmlich/113893596356295498
I believe this update should be safe for Bangle.js devices as well, since the services are created only when the device advertises them. However, I am unable to test it on one.

[Bangle.js] Device Info service and battery service

---

ui/translations/harbour-amazfish-ui-be.ts
ui/translations/harbour-amazfish-ui-cs.ts
ui/translations/harbour-amazfish-ui-de.ts
ui/translations/harbour-amazfish-ui-es.ts
ui/translations/harbour-amazfish-ui-fa.ts
ui/translations/harbour-amazfish-ui-fr.ts
ui/translations/harbour-amazfish-ui-nb_NO.ts
ui/translations/harbour-amazfish-ui-nl.ts
ui/translations/harbour-amazfish-ui-pl.ts
ui/translations/harbour-amazfish-ui-ru.ts
ui/translations/harbour-amazfish-ui-sv.ts
ui/translations/harbour-amazfish-ui-ta.ts
ui/translations/harbour-amazfish-ui-zh_CN.ts
ui/translations/harbour-amazfish-ui.ts

lupdate-qt5 . -recursive -ts ./translations/*.ts -noobsolete

Update translations strings

---

ui/qml/pages/SportsSummaryPage.qml

original merge request https://github.com/piggz/harbour-amazfish/pull/457

Fixes incorrect merge, this should optimize speed on SportSummaryPage again

---

ui/qml/pages/SportsSummaryPage.qml

I should probably check it more carefully.

SportSummaryPage cache - incorrect merge again )-;

---

ui/o2/CMakeLists.txt
ui/o2/src/CMakeLists.txt

See details in #486
I am not using strava, it would be great to verify if everything works as expected before merge.

CMake O2 version

---

ui/qml/components/DateNavigation.qml
ui/qml/pages/AnalysisPage.qml
ui/qml/pages/BatteryPage.qml
ui/qml/pages/HeartratePage.qml
ui/qml/pages/SleepPage.qml
ui/qml/pages/StepsPage.qml

Tested with ubuntu touch and kirigami

[UX] Use calendar component to browse steps/HR/.. history

---

daemon/CMakeLists.txt
daemon/src/devices/zeppos/zepposauthservice.cpp
daemon/src/devices/zeppos/zepposbatteryservice.cpp
daemon/src/devices/zeppos/zepposbatteryservice.h
daemon/src/devices/zepposdevice.cpp
daemon/src/devices/zepposdevice.h

Includes minimal changes to pass the build too.

Initial battery service for zeppos

---

daemon/CMakeLists.txt
ui/o2/src/CMakeLists.txt

See discussion at https://github.com/piggz/harbour-amazfish/issues/506
I haven't tested it so far.

Avoid use of CMAKE_INSTALL_PREFIX

---

ui/qml/pages/FirstPage.qml

On FirstPage I get some errors in the log about using anchors in a layout component. Trying to fix this.
I am afraid I can't provide a screenshot or test this in UI since I never see this part. Not sure how to trigger it.

fix usage of anchors in layout
