- translations/harbour-amazfish-ru.ts
The latest released package harbour-amazfish-0.7.1-1.armv7hl.rpm contains outdated version of the translation. The resulting UI.is only 50% translated, which is pointless. Please, update the package with this commit, because it sinchronizes some translation choices with the official Russian watch FW.
> Russian translation fixed to match the official watch FW localization

- .gitignore
- daemon/src/services/mibandservice.cpp
Whilst perusing the code to try to figure out why my Band 2's heart rate data is no longer appearing in the app, I spotted that the switch allowing the user to specify which wrist they wear their watch on specified the left wrist twice.  So I fixed it, assuming that I read the keys in the correct order.  The app builds and runs on my Xperia XA2 running SFOS 3.1.0.11.
> Fix right wrist assignment in mibandservice.cpp

- ui/qml/pages/Settings-device.qml
the time format selection was swapped, now the watch follows the gui (bug was reported by erdzas on OpenRepos comments)
> little bug-fix for time format selection 

- daemon/src/devices/abstractfirmwareinfo.h
This fixes building on Musl (and thus Alpine Linux/postmarketOS)
> Rename u_int32_t to uint32_t

- ui/ui.pro
The "-t" argument is unnecessary and unsupported by Busybox (and I guess POSIX), just drop it
> Fix compatibility with Busybox cp

- daemon/src/deviceinterface.cpp
- daemon/src/deviceinterface.h
Exposes events, supplies the enum name as string argument. Tested with a test build of slumber by matching "EVENT_APP_MUSIC", works well. 
Nonetheless: If this is rubbish, please let me know. ;)
cheers!
> expose deviceEvent as deviceEventTriggered to DBus

- daemon/src/operations/activityfetchoperation.cpp
- daemon/src/services/mibandservice.cpp
Keeping watch in local timezone allows faster GPS fixes with AGPS.
> Keep watch in local timezone

- ui/qml/components/platform.kirigami/PageListPL.qml
The code contains a few things that are unnecessary and actually break
things.
Now the page properly fills the width and the scrollbar is placed
properly
Before:
After:
> Fix Kirigami PageListPL

- rpm/harbour-amazfish.spec
Don't assume os-release exists and use lua instead of check
Follow the link below for more information:
https://rpm.org/user_doc/lua.html
> rpm: Check if KCalendarCore installed using lua

- ui/qml/pages/Settings-menu.qml
If device supports Alarms, it enables weather as a supported feature. If device supports Weather it enables feature Alarms.
This fixes the qml transposition.
> Fix Support Feature Weather

- daemon/daemon.pro
- daemon/src/devices/infinitimefirmwareinfo.cpp
- daemon/src/devices/infinitimefirmwareinfo.h
- daemon/src/operations/dfuoperation.cpp
- daemon/src/operations/dfuoperation.h
In Infinitime, the firmware (for the OTA) is provided as a DFU ZIP file. However, Amazfish does not support the ZIP file and only accept the uncompressed binary file.
This PR adds support for the ZIP file (and removes the support for the raw bin file). The name of the firmware file inside the archive and the CRC of the firmware are read from the `manifest.json` file included in the DFU archive.
> PineTime / InfiniTime : OTA now takes the DFU ZIP file

- daemon/src/devices/pinetimejfdevice.cpp
- daemon/src/operations/dfuoperation.cpp
- daemon/src/operations/dfuoperation.h
- daemon/src/operations/dfuworker.cpp
- daemon/src/operations/dfuworker.h
- daemon/src/services/dfuservice.cpp
- daemon/src/services/dfuservice.h
If an error occurs during the OTA for the PineTime running InfiniTime, the variable `m_operationRunning` is still set to 1, which prevents the user from restarting the transfer.
This PR fixes that by adding a new signal `DfuOperation::transferError`. When emitted, the slot in `DfuService::onTransferError` correctly sets the variable to 0.
I also took the opportunity to store `m_updateFirmware` in a unique_ptr to ensure that it's correctly destroyed in every cases.
> Fix error management in DfuService (for PineTime/InfiniTime)

- daemon/daemon.pro
- daemon/src/devices/infinitimefirmwareinfo.cpp
- daemon/src/devices/pinetimejfdevice.cpp
- daemon/src/devices/pinetimejfdevice.h
- daemon/src/operations/adafruitblefsoperation.cpp
- daemon/src/operations/adafruitblefsoperation.h
- daemon/src/operations/adafruitblefsworker.cpp
- daemon/src/operations/adafruitblefsworker.h
- daemon/src/services/adafruitblefsservice.cpp
- daemon/src/services/adafruitblefsservice.h
- daemon/src/services/infinitimeresourceservice.cpp
- daemon/src/services/infinitimeresourceservice.h
- ui/qml/pages/PairSelectDeviceType.qml
At InfiniTime, we are working on adding support for external resources : applications and watchfaces will be able to load images and fonts stored in the external SPI flash memory of the PineTime.
This is working quite well. See [here](https://github.com/InfiniTimeOrg/InfiniTime/issues/321) and [here](https://github.com/InfiniTimeOrg/InfiniTime/pull/1226).
Those resources are packaged into a ZIP file together with a "manifest file" that describes the mapping of the files into the watch. See [here](https://github.com/InfiniTimeOrg/InfiniTime/issues/1285).
Now, we need companion apps to implement the [upload procedure](https://github.com/InfiniTimeOrg/InfiniTime/issues/1285#issuecomment-1221605579) so users can easily update the resources from their device.
This PR contains the …
> Add support for the upload procedure of external resource for the PineTime (running InfiniTime).

- daemon/src/services/currenttimeservice.cpp
Add one missing data byte (fractions256) to be compliant with the BLE spec (CTS).
This change is needed to support [InfiniTime 1.12](https://github.com/InfiniTimeOrg/InfiniTime/releases/tag/1.12.0) which also [added this field and now requires 10 bytes to validate the data coming from the host](https://github.com/InfiniTimeOrg/InfiniTime/commit/38092fcb40695098702163ab64a06787b2dc2499).
BLE spec can be found [here (look for Current Time Service)](https://www.bluetooth.com/specifications/specs/current-time-service-1-1/) and [here (GATT Specification supplement)](https://www.bluetooth.com/specifications/assigned-numbers/).
> Current Time Service : add 1 missing data byte

- clickable.yaml
- documentation/build-instructions.md
This PR clarifies the Ubuntu Touch build instructions, mainly:
- there is no need to run Ubuntu in order to build an app for Ubuntu Touch
- the recommended and better portable way of installation is via pip, not ppa
- little clean up of clickable.yaml for better readability
> Clarify Ubuntu Touch build instructions

- daemon/src/devices/pinetimejfdevice.cpp
amazfish introduced configurable separator in February 2021 https://github.com/piggz/harbour-amazfish/commit/0638cc79c93682ea88721bf402324995775ba48f
infinitime introduced 0x00 separator for notification content in April 2021
https://github.com/InfiniTimeOrg/InfiniTime/commit/03de1c67393fcb99b5987514be6f470349c57c0f
Using 0x00 separator will improve layout notifications in PineTime. See screenshots.
> Send title separated by 0x00 from rest of notifications

- README.md
- click/manifest.json.in
- click/run.sh
- clickable.yaml
- ui/ui.pro
setting application name to uk.co.piggz.amazfish, because This is the unique  for your app. It must match exactly the "name" field in your click's manifest.json and must be all lowercase letters. For example: "openstore.openstore-team", where "openstore" is the app and "openstore-team" is the group or individual authoring the app. see https://open-store.io/submit
fix TRANSLATION folder, because follwing error message in logs <command-line>: warning: "TRANSLATION_FOLDER" redefined <command-line>: note: this is the location of the previous definition
The clickable.yaml must contain whole path, otherwise build reports following error message:
Files to install not found with pattern "libKDb3.so*"
> fix build with ubports

- lib/src/weather/currentweather.h
- ui/qml/pages/AddCityPage.qml
- ui/src/harbour-amazfish-ui.cpp
I wasn't sure which city is currently configured in the layout. I have extended the dialog to display the current city name and current temperature, as shown in the screenshot below:
There can also be a prefix such as 'Current city.' Personally, I think it is enough to display just the city name.
```
LabelPL {
text: qsTr("Current city: %1 %2")
.arg(page.currentCity)
.arg((weather.temperature !== 0) ? " " + (weather.temperature-273) + "˚C" : "")
}
```
Additionally, an icon can be added and displayed on the same line, for example, using icons from https://erikflowers.github.io/weather-icons/
> Improve weather ux

- daemon/src/deviceinterface.cpp
Caller name can also contain symbols which needs to be transliterated. The BLE message is composed independently so it must be transliterated also independently.
> Transliterate also caller name

- daemon/src/devices/huamidevice.cpp
- daemon/src/devices/pinetimejfdevice.cpp
- daemon/src/services/alertnotificationservice.cpp
- daemon/src/services/alertnotificationservice.h
I am not sure if this works properly also on other smartwatches, but on PineTime this definitely helps. 
It seems generic alert message is used for phone call, but it is composed in different way. 
The alert is
category (one byte ) + alert_type=1 ( one byte ) + icon(one byte)  + sender (32 bytes) + separator (one byte) +subject (128bytes) + separator=\n (two bytes) + message (128bytes)
PineTime doesn't counts lenght sender+subject+message, together and clips it to 100 bytes
The incommingCall() composes message like this
03 01 + caller_id
I believe that header should be 3 bytes (I have added 0x01 for icon)
03 01 01 + caller_id
And finally  proof with picture:
The notification was send from debug dialog.
> There was missing first letter in notification

- click/run.sh
- clickable.yaml
Actually there is no reason to disable systemd. Daemon is started as systemd --user unit. The only difference is that unit lives in $HOME/.config/systemd/user/harbour-amazfish.service
> Enable systemd in Ubuntu Touch

- ui/qml/components/DownloadDataMenuItem.qml
- ui/qml/components/platform.uuitk/PageMenuItemPL.qml
- ui/qml/components/platform.uuitk/StylerPL.qml
- ui/qml/pages/DebugInfo.qml
- ui/qml/pages/SportPage.qml
- ui/qml/pages/SportsSummaryPage.qml
- ui/qml/pages/StravaSettingsPage.qml
The menus in ubuntu touch containing only one item collapses into action button without label. The button is not visible without icon.
For example the refresh MenuItem on DebugInfo Page looks like this after changed:
Additionally, the iconSource in [PageMenuItemPL.qml](https://github.com/piggz/harbour-amazfish/compare/master...jmlich:singleMenuItem?expand=1#diff-8f2ebc8656ea33b5f58d6510f9b46224d8b3d899d56d6838a80fb2be25d00841) must be done other way around in order to work at least with current release with Ubuntu Touch.
The icons are set in order to keep working SailfishOS port even when the icon is not set. This is a case of following icons
```
property string iconStravaLogin: "image://theme/user-admin"
property string iconUploadToStrava: "image://theme/share"
property string …
```
> Single menu item must have icon in Ubuntu Touch

- ui/qml/pages/FirstPage.qml
- ui/qml/pages/PairPage.qml
The test case is following: 
User tries to cancel old pairing and to pair new smartwatch
- click to Pair button
- confirm UnPairing
- select smart watch type (e.g. PineTime)
- select smartwatch according to advertised name or mac address (e.g. InfiniTime CC:88:11:33:FF:88)
- after successful pairing should be shown first page, but it isn't
Explanation:
The DialogPL implements onAccepted method. The method it self performs app.pages.pop(), then unpairAccepted() is invoked and calls app.pages.replace(PairSelectDeviceType). The consequence is that the FirstPage is disposed and app.rootPage is set to null. 
I am not 100% sure if this behaves same with all UI flavors. My best guess is that is this is that yes. The code shows that kirigami, uuitk, and qtcontrols implementation does .pop() it …
> Return back to rootPage after pairing, busy indicator centered

- ui/qml/components/platform.uuitk/StylerPL.qml
- ui/qml/pages/PairPage.qml
The explanation is the same as https://github.com/piggz/harbour-amazfish/pull/295 Single item menus are collapsed directly into button. The text description is not used. The button is not visible when haven't the icon.
I haven't realized that "scan button" is affected also because the second menu item is visible conditionally.
> Bluetooth scan should have also icon otherwise is not visible

- daemon/src/devices/pinetimejfdevice.cpp
The service() function expects service uuid instead of characteristics uuid. As a consequence the information() function returns empty QString() instead of expected value. The function is called in Component.onCompleted of StepsPage, this sets _InfoSteps to "" and user can see 0 on the FirstPage
Steps to reproduce:
- open application, there is non-zero number of the FirstPage
- go to StepsPage and back
- Number of steps should be non-zero number
> PinetimeJFDevice::information returning empty string

- daemon/src/transliterator.cpp
- daemon/src/transliterator.h
When the notification (e.g. from telegram) contain only emoji, the result is empty message.
I haven't found suitable transliteration of emojis in icu so I have created some mapping similar to gadgetbridge
https://github.com/Freeyourgadget/Gadgetbridge/blob/0f7fa7593130a51d7d95a90301cdfe1bd63ba447/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/EmojiConverter.java#L29
> Transliterate also emojis

- daemon/src/deviceinterface.cpp
- daemon/src/deviceinterface.h
- ui/qml/pages/DebugInfo.qml
- ui/src/daemoninterface.cpp
- ui/src/daemoninterface.h
I was checking code of fetchLogs() and it seems that `DaemonInterfaceInstance.miBandService()` is not accessible in UI. In my opinion the code should be as is in pull request. However, I don't have a device to test.
> fetchLogs not accessible from ui

- documentation/build-instructions.md
repository url does not match
clickable package could be build at once with libs and app, skip-review is necessary build when unconfined apparmor policy is used.
> fix build instructions

- ui/qml/pages/PairPage.qml
The bluetoothManager.usableAdapter is null when the bluetooth is turned off. This patch popups dialog with error message when the discovery is triggered and bluetooth adapter is not available.
Closes #131
> Show message when bluetooth is off

- daemon/daemon.pro
- daemon/src/deviceinterface.cpp
- daemon/src/devices/abstractdevice.cpp
- daemon/src/devices/abstractdevice.h
- daemon/src/devices/pinetimejfdevice.cpp
- daemon/src/devices/pinetimejfdevice.h
- daemon/src/realtimeactivitysample.cpp
- daemon/src/realtimeactivitysample.h
Until Infinitime implements physical activity monitor service (see https://github.com/InfiniTimeOrg/InfiniTime/issues/749) or similar mechanism to store and transfer sampled activity we can use only real time data from heart rate monitor and from motion service .
Closes https://github.com/piggz/harbour-amazfish/issues/274
> Sampling of PineTime realtime activity and store it into mi_band_activity table

- documentation/build-instructions.md
I can see, that pulseaudio-devel wasn't added into documentation.
> update documentation for sfos

- ui/qml/components/platform.uuitk/TimePickerDialogPL.qml
Ubuntu touch provides native date picker which can be used for time:
https://ubports.gitlab.io/docs/api-docs/lomiriuserinterfacetoolkit/qml-lomiri-components-pickers-datepicker.html
```
import Lomiri.Components.Pickers 1.0
DatePicker {
mode: "Hours|Minutes"
}
```
In the end it looks like this:
> Use native component for TimePicker

- daemon/src/services/alertnotificationservice.cpp
The implementation in GadgetBridge sends icon only when the 
```
if (alert.getCategory() == AlertCategory.CustomHuami) {
```
See https://github.com/Freeyourgadget/Gadgetbridge/blob/275deb4d06de6b64c0d7e73d13f6f2ad2879fe25/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/btle/profiles/alertnotification/AlertNotificationProfile.java#L106
The same issue was basically with Phone Calls https://github.com/piggz/harbour-amazfish/pull/286, which contain category IncomingCall, so icon byte is not expected.
Additionally, mapSenderToIcon() was triggered twice even icon variable already contain the result.
> Only category CustomHuami should have icon in header

- daemon/src/services/alertnotificationservice.cpp
- daemon/src/services/alertnotificationservice.h
There is an enum AlertCategory in AlertNotificationService.h which contain same value. In my opinion is code nicer when enum is used.
> Use AlertCategory::CustomHuami instead of 0xfa magic constant

- daemon/src/deviceinterface.cpp
steps to reproduce:
paired device: asteroid os - battery 95%
pair new device: pinetime - battery 5%
Notification contain following message `Battery level now 95 %`, but it should report 5%
> report current value, not previous one

- ui/qml/pages/Settings-alarms.qml
- ui/qml/pages/Settings-device.qml
- ui/qml/pages/Settings-huami-shortcuts.qml
- ui/qml/pages/Settings-profile.qml
Fixes #339 
It seems app.pages.pop() calls destructor of the Page including Timer before it is triggered
> Pop after timer refresh daemon

- ui/qml/components/platform.uuitk/TimePickerDialogPL.qml
I have noticed, that TimePicker sets time property, but Alarm is using hour and minute. The lomiri DatePicker provides read/only hours and minutes properties. I am not sure if is needed to provide hour and minute as read/write property. It seems Alarm doesn't need that. 
There is another use in ui/qml/pages/Settings-profile.qml, but I don't have time to investigate it now. I may get to this later, but would rather not promise anything.
https://ubports.gitlab.io/docs/api-docs/lomiriuserinterfacetoolkit/qml-lomiri-components-pickers-datepicker.html
> Alarm doesn't store TimePicker value

- daemon/src/devices/banglejsdevice.cpp
1. Incoming calls
From specifications of notifications of gadgetbridge (https://www.espruino.com/Gadgetbridge), cmd can be 
t:"call", cmd:"accept/incoming/outgoing/reject/start/end", name: "name", number: "+491234" - call
example shows :
GB({"t":"call","cmd":"incoming","name":"name","number":"+441234123123"})
Tried this way and incoming calls show on my bangle.js 2
I didn't check however how to accept or refuse calls...
2. Notifications (sendAlert)
Put an unique identifier.
Also, filter out messages which have an empty body and subject. Not convinced 100%, but something similar is done for instance for MiBandService::sendAlert
For me, it concerns mails which sends two notifications, the second with "courriel" (so in French) in the sender field, with empty subject and message.
I suppose it …
> Banglejs : Improvement over notifications

- daemon/daemon.pro
- daemon/src/deviceinterface.cpp
Same pulse audio api is available on Ubuntu Touch.
I was testing the feature with Amazfit NEO.
> Enable find my phone on Ubuntu Touch

- daemon/src/bipactivitydetailparser.cpp
Add TotalTimeSeconds, DistanceMeters, AverageHeartRateBpm and MaximumHeartRateBpm to tcx file. Include additions of Steps and Calories correction from https://github.com/piggz/harbour-amazfish/pull/345 that fixes https://github.com/piggz/harbour-amazfish/issues/343. In addition, adding the DistanceMeters field fixes the problem of not displaying the distance traveled in treadmill exercises on different platforms. (example [before](https://www.strava.com/activities/10996353233) and [after](https://www.strava.com/activities/11010825842) correction)
> Add some info to exported tcx file

- ui/harbour-amazfish-ui.appdata.xml
As is mentioned in https://github.com/flathub/flathub/pull/5173 the appdata.xml should be part of main repository. 
The gnome-software listing and flathub listing (which I am not able to preview) is build from that file
There is Changelog section which should be updated with new release.
It is possible to validate file using following command
```
appstream-util validate harbour-amazfish-ui.appdata.xml
```
The flatpak provides yet another validator tool which provides valuable information. I have adjusted changelog first letters to upper case according to its output.  
```
flatpak run --command=flatpak-builder-lint org.flatpak.Builder appstream harbour-amazfish-ui.appdata.xml
```
> Add appdata.xml

- ui/amazfish.qrc
I have spotted that some pictures are not shown in `FLAVOR=qtcontrols`.
In logs I can see following message:
```
qrc:/qml/components/DeviceButton.qml:14:5: QML Image: Cannot open: qrc:/qml/pics/devices/asteroidos.png
```
I have updated all files in directory as follows:
```
for i in $(ls -1|sort); do echo "        <file>qml/pics/devices/$i</file>"; done
```
> Add missing pics into qrc

- daemon/src/devices/huamidevice.h
- daemon/src/devices/neodevice.cpp
it seems that max length of message is limited.
The specification says 18 characters. The screen shows only "+1" or "+2" anyway.
Code worked for me, but it would be great if @kirbylife can look at it as well.
> AmazfitNeo notification is using AlertNotificationService

- ui/amazfish.qrc
Similar to https://github.com/piggz/harbour-amazfish/pull/359
qtcontrols flavor requires everything in qrc. This could be solved probably by some script in future.
> Add BatteryPage to qrc

- daemon/src/deviceinterface.cpp
Sanity check if firmware info is null to avoid crash. I am not able to test it.
Related to #174
> Avoid crash if firmware info is null

- README.md
- daemon/daemon.pro
- daemon/src/harbour-amazfish-daemon.cpp
- daemon/translations/harbour-amazfishd-cs.ts
- daemon/translations/harbour-amazfishd-pl.ts
- daemon/translations/harbour-amazfishd.ts
- ui/qml/pages/DebugInfo.qml
- ui/translations/harbour-amazfish-ui-cs.ts
Fixes #331
I have renamed *.ts files and updated them
```
for i in *.ts; do echo $i; x=${i/amazfish-ui/amazfishd}; mv $i $x;  done
lupdate-qt5 -recursive -no-obsolete . -ts ./translations/*.ts
```
it was necessary to add `language="ru"` and `language="cn_ZH"` to make lupdate work
> Translations for daemon

- ui/amazfish.qrc
- ui/src/harbour-amazfish-ui.cpp
Previously, there were generic icon visible in windowed mode.
I am not sure if is needed to set icon also for Sailfish or Ubuntu Touch. Ubuntu Touch have windowed mode, but I don't have device to test it. For sure it is necessary to set right file path for each of them.
> Show window icon for Kirigami

- daemon/src/harbour-amazfish-daemon.cpp
- ui/qml/components/platform.kirigami/ListItemPL.qml
- ui/qml/components/platform.kirigami/PagePL.qml
- ui/qml/components/platform.qtcontrols/TimePickerDialogPL.qml
- ui/qml/harbour-amazfish.qml
- ui/src/daemoninterface.cpp
- suppress some kirigami warnings
- add some information to pairing qDebug
- fix timepicker when getHours() is NaN
> [kirigami] Minor improvements

- ui/harbour-amazfish-ui.appdata.xml
Rebuild of flatpak reports following error:
```
$ flatpak-builder --verbose --user --install --force-clean build-dir uk.co.piggz.amazfish.json
...
Error: Error on line 68 char 21: Element “description” was closed, but the currently open element is “p”
...
```
> typo in appdata xml

- .github/workflows/sailfishos.yml
- documentation/build-instructions.md
SDK docker image was updated 
https://github.com/CODeRUS/docker-sailfishos-platform-sdk/issues/10
Currently, it seems repository https://repo.sailfishos.org/obs/home:/piggz:/kf5/ doesn't work so I have replaced it with chum repo https://repo.sailfishos.org/obs/sailfishos:/chum/4.6_i486/
> Update SFOS SDK CI image to 4.6.0.13

- click/disable-armhf-version-check.patch
- click/enable-clang-cross-compiling.patch
- clickable.yaml
It finally works! Currently it looks like this:
> Add missing mapbox components for Ubuntu Touch

- .github/workflows/flatpak.yml
See https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
Fixes this issue https://github.com/piggz/harbour-amazfish/actions/runs/10757653199/job/29831944241
> CI: fix deprecated actions/upload-artifact@v2

- ui/qml/pages/FirstPage.qml
- ui/qml/pages/SportPage.qml
Some of the icons on the main screen and in sports page are missing a left margin. This PR does add margins.
Before:
After:
> add missing left margins to icons

- ui/qml/pages/Settings-app.qml
It seems the cboLocalAdapter.value is read only
```
[20240920 10:25:57.635 CEST W] qrc:/qml/pages/Settings-app.qml:30 - qrc:/qml/pages/Settings-app.qml:30: TypeError: Cannot assign to read-only property "value"
```
It seems other ComboBoxPL objects are using currentIndex instead of value (which is alias to ComboBox.currentText).
I wasn't able to use .index(),.data(), and roles, so I have added .get() method into AdapterModel into https://github.com/piggz/qble/pull/2
> Selection of adapter in Application Settings doesn't work 

- ui/qml/pages/FirstPage.qml
Unless I have missed it, but when opening the app the `_infoSteps` value does not get initialized. Only when visiting the steps page or manually uploading or so the var is assigned a value. So I suggest to initialize it - if a device is connected - in the onCompleted event.
> add init procedure for steps

- documentation/build-instructions.md
This PR will update the repo links for the two sailfish plugins. It will also extend the note for UT build instructions to mention the libraries, since the command given will build both, the app and the libs.
Important for myself was, that the libs need to be build against the target architecture e.g. arm64. So this command needs to be run with a device attached. Or libs need to be build manually by specifying the correct architecture. Simply building will use the hosts arch which will fail. I hope my last rephrasing makes that clearer.
> Update build instructions

- ui/qml/pages/StepsPage.qml
This PR will use the same locale number format for steps as on [FirstPage](https://github.com/piggz/harbour-amazfish/blob/master/ui/qml/pages/FirstPage.qml#L186). 
It will also drop showing the steps of the last day when steps are zero. I personally find it confusing to see a number there if I know I didn't do any steps. On other pages also zero is shown if there is no reading (yet). So I suggest dropping that part and show zero steps if there are zero steps.
> show locale number format for steps

- ui/qml/pages/HeartratePage.qml
This PR will do two things in heart rate page:
1. it will use round instead of floor to calculate the category values to avoid larger differences when summing all up (sum should be 100%, but with floor can be easily 5% less, now at most 1% rounding difference)
2. it will add a third column with the actual threshold values which are used to calculate the categories, those values are important in my opinion, because a user might want to set a bpm warning on their watch (bip allows to do that) when exercising, but for that they need to now the value
> add column with bpm tresholds and use round instead of floor

- daemon/src/devices/banglejsdevice.cpp
- daemon/src/devices/banglejsdevice.h
I have done brief testing with bangle.js device (during conference lunch break) and kirigami flavor (qt 5.15.8) . It worked for me. There is `#ifdef` for SailfishOS which wasn't tested (i.e. blind implementation).
> Fixes #421: setTime upon connection to bangle.js

- ui/qml/components/platform.qtcontrols/BusyIndicatorPL.qml
- ui/qml/components/platform.silica/PageListPL.qml
- ui/qml/pages/PairPage.qml
I was trying to make some cleanup of PairingPage. I have found an issue with missing BusyIndicator https://github.com/piggz/harbour-amazfish/issues/406
This pull request intent is to demonstrate what change was done in order to make BusyIndicator visible in pairing page.
> Show BusyIndicator in kirigami (refactor _placeholderText)

- daemon/src/devices/asteroidosdevice.cpp
- daemon/src/devices/banglejsdevice.cpp
- daemon/src/devices/pinetimejfdevice.cpp
I have discovered that `QBLEDevice::connectToDevice();` is used instead of `QBLEDevice::pair();` in InfiniTime. It seems to be legacy code intended to fix connection issues with older PineTime firmware.
The same code was copied and pasted into AsteroidOS.
I have tested this behavior with PineTime and AsteroidOS on Ubuntu Touch (Volla1), SailfishOS (PinePhone), and Kirigami (my desktop setup), and it works in my opinion much better than before.
I have noticed the same thing in Bangle.js code. I assume it will work better as well, but I currently don't have a device to test. Occasionally, I can borrow a device for testing, but it might take some time.
I have also observed that on Ubuntu Touch, the "system-wide" Authentication Agent seems to appear only when the Bluetooth Settings dialog is …
> pair function shoud invoke QBLEDevice::pair()

- ui/qml/components/platform.kirigami/DialogPL.qml
- ui/qml/components/platform.qtcontrols/DialogPL.qml
- ui/qml/pages/FirstPage.qml
In c48f79b96e6e81e2e01f60a0c36ec7706d6887b6 there was a fix of Dialog behaviour for Device Unpair operation. This broke DatePicker Dialog (User Settings -> Birthday) .
In this fix is used acceptDestination variable show the Unpair works with previous implementation and DatePicker works as well.
Same issue applies to TimePicker Dialog as well.
The change may affect also unpair page
> [kirigami] DatePicker dialog doesn't pop() when accepted

- ui/harbour-amazfish-ui.appdata.xml
Flatpak recommends settings some brand colors. 
https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines/#has-primary-brand-colors
I took those two colors. However, I am not artist and my sense of good colors is limited:
Light `#ff8446`:
Dark `#3a1d11`:
> Add some brand colors

- ui/qml/pages/SleepPage.qml
It seems String prototype padStart() is not available on SailfishOS
Log contain following message:
```
Nov 29 07:06:12 PinePhone i[3056]: [W] unknown:94 - file:///usr/share/harbour-amazfish-ui/qml/pages/SleepPage.qml:94: TypeError: Property 'padStart' of object 0 is not a function
```
> fixes #432: avoid padStart on SailfishOS

- daemon/src/devices/neodevice.cpp
It seems Amazfit NEO is using 8 bytes for activity samples. 
In Gadgetbridge the AmazfitNeoSupport is at [1], the inheritance points to MiBand5Support [2] and there is return 8 in getActivitySampleSize(). Data parsing it self is in [3].
[1] https://codeberg.org/Freeyourgadget/Gadgetbridge/src/branch/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/huami/amazfitneo/AmazfitNeoSupport.java
[2] https://codeberg.org/Freeyourgadget/Gadgetbridge/src/branch/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/huami/miband5/MiBand5Support.java
[3] https://codeberg.org/Freeyourgadget/Gadgetbridge/src/branch/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/huami/operations/fetch/FetchActivityOperation.java
[4] …
> [Amazfit NEO] Use sampleSize 8 for activity fetch

- ui/qml/components/platform.uuitk/PopupPL.qml
- ui/qml/pages/DebugInfo.qml
- ui/src/harbour-amazfish-ui.cpp
I am wondering how the PopupPL should look like. In SailfishOS it is implemented as notification. 
This is a draft how it could look like:
I am not sure why isn't the notification next other notification. Probably some parameter is wrong
The other option is to use Lomiri.Components.Popups. See https://ubports.gitlab.io/docs/api-docs/lomiriuserinterfacetoolkit/qml-lomiri-components-popups-popuputils.html
> [Ubuntu Touch] Popup using notification

- rpm/harbour-amazfish.spec
I can see following error messages in journal on pinephone when the mapboxgl-qml package is missing
```
led 10 15:32:33 PinePhone i[4969]: [W] unknown:1283 - file:///usr/lib64/qt5/qml/Sailfish/Silica/PageStack.qml:1283:13: QML AnimatedLoader: (file:///usr/share/harbour-amazfish-ui/qml/pages/SportPage.qml:3:1: module "MapboxMap" is not installed
import MapboxMap 1.0
^)
led 10 15:32:33 PinePhone i[4969]: [W] unknown:113 - file:///usr/share/harbour-amazfish-ui/qml/pages/SportsSummaryPage.qml:113: Error: Cannot assign to non-existent property "activitytitle"
```
> SportPage is not shown when mapboxgl-qml is not installed

- ui/qml/components/GraphData.qml
I noticed that the y-axis labels are overlapping because the text is wrapped.
See the difference in the screenshot.
> Don't wrap axis labels

- ui/qml/pages/Settings-huami-shortcuts.qml
I have noticed that some items are not translated:
> Add translations to huami items

- ui/qml/components/platform.uuitk/PopupPL.qml
The popup is used for every synchronization quite often. The sound is a little annoying. Additionally, it hard codes some random system sound.
I am sorry for noise, I should see this before sending pull request ;-(
> [Ubuntu Touch] Popup: Remove sound, because its annoying

- daemon/src/devices/huamidevice.cpp
- daemon/src/devices/huamidevice.h
Fixes: #375
I am not sure if this is right solution to the issue. However, I am able to connect to Amazfit NEO with this fix.
I was trying to improve debug messages to be able to find source of issue.
> [huami] Avoid repeated initialization

- daemon/src/services/mibandservice.cpp
Services should emit a service event, which a device will udnerstand, and re-trigger as an AbstractDevice event.
Fixes #448
Fixes #423
> Emit the correct value to decline a call.

- daemon/src/deviceinterface.cpp
According to the documentation https://doc.qt.io/qt-6/qcoreapplication.html#quit, `QCoreApplication::quit()` works only when `app.exec()` is running.
The `DeviceInterface::registerDBus` function is invoked within the `DeviceInterface` constructor, which occurs before `app.exec()`. As a result, the second instance of the daemon fails to register the DBus interface but does not exit immediately.
Steps to reproduce the issue:
-    Try to run two instances of the daemon.
-    Expected result: The second instance should exit immediately upon startup.
> QCoreApplication::quit() is not working before app.exec()

- daemon/src/services/batteryservice.cpp
I have seen some segfaults because of invalid battery service data. 
Similar checks are also in other services. For example:
https://github.com/piggz/harbour-amazfish/blob/d0508a6dbdd3cf6b2f380f3512d15d1956acbc7c/daemon/src/services/infinitimemotionservice.cpp#L33-L37
> Battery service payload format check

- daemon/src/deviceinterface.cpp
- daemon/src/deviceinterface.h
- ui/qml/pages/FirstPage.qml
- ui/qml/pages/PairPage.qml
- ui/src/daemoninterface.cpp
- ui/src/daemoninterface.h
One of my observations is that trying to pair already paired devices doesn't work. This should improve the experience when hopping between devices. 
Right now it is not very well tested, but I believe this is one of scenarios I do very often.
CI failed also because https://github.com/piggz/harbour-amazfish/pull/468
> [qble] call bluez::adapter::RemoveDevice() to unpair device

- ui/qml/pages/SportsSummaryPage.qml
According to my measurement on desktop the loading of Page changed from 1.6 s to 0.1 s after first load of data. It seams there is still some ugly leak which is causing delay in rendering of the page.
I was testing that just with kirigami right now.
Details are shown here: https://youtu.be/wfLNFML_pUA
> [SportSummaryPage] Use sharead Image.source to accelerate rendering of Icons and use Loader

- daemon/src/devicefactory.cpp
- ui/qml/pages/PairPage.qml
- ui/qml/pages/PairSelectDeviceType.qml
Bangle.js is supported also by other devices. Gadget bridge is using following regexp:
https://github.com/Freeyourgadget/Gadgetbridge/blob/a0948ee1cbc2a870f91d313f8e37df5f524465f7/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/banglejs/BangleJSCoordinator.java#L75
I have reworked PairSelectDevice type in order to define regexp rather than aliases. The DeviceFactory is using startsWith anyway.
I was also wondering if we should rework connect page to match Device class other way around. The Gadgetbridge shows all hardware in bluetooth scan and allows pairing only when match with some pattern. Otherwise it can be useful allowing to pair with certain type even when regular expression doesn't match. Huami devices have big overlap, so It may work partially even without changes …
> Change filter to regexp, add Espruino to Bangle.js device

- daemon/CMakeLists.txt
- daemon/src/deviceinterface.cpp
- daemon/src/deviceinterface.h
- lib/src/amazfishconfig.h
- ui/qml/pages/Settings-app.qml
Allows to switch automatically between silent and general profile when smartwatch connected and disconnected.
I have tested the feature with Ubuntu Touch and SailfishOS
Fixes: #353
> Automatic switching of audio profiles

- click/harbour-amazfish.apparmor
- clickable.yaml
- daemon/CMakeLists.txt
- daemon/src/achievements.cpp
- daemon/src/achievements.h
- daemon/src/deviceinterface.cpp
- daemon/src/deviceinterface.h
The goal is to display the message `%1 steps made today` on the lock screen, similar to the example in the UBports documentation:
https://docs.ubports.com/de/latest/appdev/guides/user-metrics.html
I suspect there may be an issue with internationalization (i18n), since Amazfish uses lupdate and lrelease, while other UBports apps use gettext. The libuserinput library tries to set the textDomain() to load translations independently.
> Ubuntu touch user metrics

- daemon/src/deviceinterface.cpp
- daemon/src/deviceinterface.h
- daemon/src/devices/abstractdevice.h
- daemon/src/devices/asteroidosdevice.cpp
- daemon/src/devices/asteroidosdevice.h
- daemon/src/devices/banglejsdevice.cpp
- daemon/src/devices/banglejsdevice.h
- daemon/src/devices/dk08device.cpp
- daemon/src/devices/dk08device.h
- daemon/src/devices/huamidevice.cpp
- daemon/src/devices/huamidevice.h
- daemon/src/devices/pebbledevice.cpp
- daemon/src/devices/pebbledevice.h
- daemon/src/devices/pinetimejfdevice.cpp
- daemon/src/devices/pinetimejfdevice.h
- daemon/src/devices/zeppos/zepposnotificationservice.cpp
- daemon/src/devices/zeppos/zepposnotificationservice.h
- daemon/src/devices/zepposdevice.cpp
- daemon/src/devices/zepposdevice.h
- daemon/src/services/asteroidnotificationservice.cpp
- daemon/src/services/asteroidnotificationservice.h
- lib/src/amazfish.h
- ui/src/daemoninterface.cpp
The WatchNotification struct was moved into `lib/src/amazfish.h` to be able to reference that from UI. Additionally, I have created toQVariantMap fromQVariantMap conversions to be able pass it via dbus.
The interface function was overloaded to be able use it via dbus:
```
void DeviceInterface::sendAlert(const QVariantMap &notification, bool allowDuplicate)
void DeviceInterface::sendAlert(const Amazfish::WatchNotification &notification, bool allowDuplicate)
```
> Move WatchNotification into amazfish.h, add conversion to QVariantMap

- daemon/src/devicefactory.cpp
- daemon/src/devicefactory.h
- daemon/src/deviceinterface.cpp
- lib/src/amazfishconfig.h
- ui/qml/components/DeviceListModel.qml
- ui/qml/pages/FirstPage.qml
- ui/qml/pages/PairDevicePage.qml
Next step in pairing refactoring. This allows to use random hardware with specific implementation. Next step should be dialog to show DeviceListModel and allow to select deviceType manually. 
Important for release notes: It is necessary to pair device again.
I need to test it carefully
> Use DeviceType for DeviceFactory instead of name

- ui/qml/components/platform.qtcontrols/LabelPL.qml
- ui/qml/pages/SportsSummaryPage.qml
SFOS/UBports Label doesn't padding by default either
Left with padding (old version), Right without padding (new version)
Left with padding (old version), Right without padding (new version)
However, some settings pages needs now explicit padding for labels, but this is at least the same as other platforms.
> kirigami LabelPL shoudn't have default padding

- ui/qml/pages/SportPage.qml
Sport Icon wasn't visible at all
Map icons wasn't visible well, now is color taken from theme.
ubports dark
ubports light
sailfish os
kirigami
> Fix sport details icons

- ui/qml/pages/SportsSummaryPage.qml
TimeLabel and DateLabel are now aligned
- the right padding was Medium and Small
- the width wasn't defined on Date.
Ubuntu Touch
previously SFOS
now SFOS
now Kirigami
> Make sure that items have same alignment
